version: "3.8"
services:
  grass:
    build: .
    container_name: grass-miner
    restart: on-failure:1
    environment:
      - GRASS_USER=USER
      - GRASS_PASSWORD=PASSWORD
      - GRASS_CRX_NAME=grass-4.20.2.crx
      - GRASS_CRX_EXTENSION_ID=lkbnfiajjmbhnfledhphioinpickokdi
    ports:
      - "8000:80"
    volumes:
      - ./data:/app/data
