version: "3.8"
services:
  grass:
    build: .
    container_name: grass-miner
    restart: always
    environment:
      - GRASS_USER=$GRASS_USER
      - GRASS_PASSWORD=$GRASS_PASSWORD
      - GRASS_CRX_NAME=$GRASS_CRX_NAME
      - GRASS_CRX_EXTENSION_ID=$GRASS_CRX_EXTENSION_ID
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./data:/app/data
