{
 "title": "Grass miner Dashboard",
 "description": " Dashboard for grass-miner with prometheus",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(grass_network_quality,job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(grass_network_quality,node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table",
   "description": "Summary of Grass nodes",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grass_network_quality{job=~\"$job\"}"
    },
    {
     "expr": "grass_node_earnings{job=~\"$job\"}"
    },
    {
     "expr": "grass_time_connected{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Network Quality Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "grass_network_quality{job=~\"$job\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Earning Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "k" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grass_node_earnings{job=~\"$job\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Earning per hour",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max_over_time(grass_node_earnings{job=~\"$job\"}[1h]) * 1000 - max_over_time(grass_node_earnings{job=~\"$job\"}[1h] offset 1h) * 1000",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "node" },
  {
   "title": "Network Quality",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grass_network_quality{job=~\"$job\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Earning",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "k" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grass_node_earnings{job=~\"$job\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Time connected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grass_time_connected{job=~\"$job\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Network Quality",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "grass_network_quality{job=~\"$job\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Earning per hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max_over_time(grass_node_earnings{job=~\"$job\", node_name=~\"$node\"}[1h]) * 1000 - max_over_time(grass_node_earnings{job=~\"$job\", node_name=~\"$node\"}[1h] offset 1h) * 1000 ",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}